name: 'Generate Repository Feed'
description: 'Generate a RSS Atom feed from the commits of a GitHub repository'
inputs:
  user:
    description: 'GitHub username'
    required: true
  repo:
    description: 'Repository name'
    required: true
outputs:
  feed:
    description: 'The generated Atom feed'
  main_script:
    description: 'main script for execute GitHub Action'
runs:
  using: 'node20'
  main: 'src/main.js' # for Development
# main:release/index.js # for Production
