name: 'Generate Repository Feed'
description: 'Generate a RSS Atom feed from the commits of a GitHub repository'
inputs:
  user:
    description: 'GitHub username'
    required: true
  repo:
    description: 'Repository name'
    required: true
outputs:
  feed:
    description: 'The generated Atom feed'
runs:
  using: 'node20'
  main: ${{ fromJSON(steps.get-entry-point.outputs.entry-point) }} # エントリーポイン

steps:
  - id: get-entry-point
    run: |
      # mainブランチの場合
      if ${{ github.ref == 'refs/heads/main' }}
      then
        echo "::set-output name=entry-point::'release/index.js'"
      else # developブランチの場合
        echo "::set-output name=entry-point::'src/main.js'"
      fi
