name: 'Generate Repository Feed'
description: 'Generate a RSS Atom feed from the commits of a GitHub repository'
inputs:
  user:
    description: 'GitHub username'
    required: true
  repo:
    description: 'Repository name'
    required: true
outputs:
  feed:
    description: 'The generated Atom feed'
runs:
  using: 'composite'
  steps:
    - name: check branch
      id: check-branch
      run: |
        echo "$GITHUB_REF"
        if [[ $GITHUB_REF =~ /main$ ]]; then
          echo "main branch"
        else
          echo "develop branch"
        fi
      shell: bash
