name: 'Generate Repository Feed'
description: 'Generate a RSS Atom feed from the commits of a GitHub repository'
inputs:
  user:
    description: 'GitHub username'
    required: true
  repo:
    description: 'Repository name'
    required: true
outputs:
  feed:
    description: 'The generated Atom feed'
runs:
  using: 'node20'
  main: 'release/index.js'
