name: Generate RSS Feed

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-feed:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - run: npm install

      - name: Generate Feed
        id: generate-feed
        uses: atsushifx/commit2feed@develop
        with:
          user: 'atsushifx'
          repo: 'commit2feed'

      - name: Save Feed
        run: |
          mkdir -p rss
          cat <<'EOF' > rss/feeds.xml
          ${{ steps.generate-feed.outputs.feed }}
          EOF

      - name: Upload Feeds
        uses: actions/upload-artifact@v4
        with:
          name: feeds
          path: rss/feeds.xml
