name: Generate RSS Feed

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-feed:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: develop

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate Feed
        id: generate-feed
        uses: atsushifx/commit2feed@develop
        with:
          user: 'atsushifx'
          repo: 'commit2feed'

      - name: Save Feed
        run: |
          mkdir -p rss
          cat <<'EOF' > rss/feeds.xml
          ${{ steps.generate-feed.outputs.feed }}
          EOF

      - name: Upload Feeds (by Commit)
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Actions User"
          git add rss/feeds.xml
          git commit -m "Update RSS Feed"
          git push
